### ISSUE TITLE
[Bug]: Game will not start up when EndlessIDs is enabled

### ISSUE THREAD

**Issue by wheredoyouthinkyourelooking** [FalsePattern/EndlessIDs#64]
### OS

Windows

### GPU

Intel

### Game log

[04:46:23] [main/DEBUG] [FML/]: Injecting tracing printstreams for STDOUT/STDERR.
[04:46:23] [main/INFO] [FML/]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[04:46:23] [main/INFO] [FML/]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_332, running on Windows 10:amd64:10.0, installed at C:\Users\REDACTED\Onedrive - REDACTED - Files\Downloads\MultiMC\liberica-jdk1.8.0_332-windows-x64\jdk1.8.0_332-windows-x64\java-windows\jre
[04:46:23] [main/DEBUG] [FML/]: Java classpath at launch is [REDACTED]
[04:46:23] [main/DEBUG] [FML/]: Java library path at launch is C:/Users/REDACTED/Onedrive - REDACTED - Files/Downloads/MultiMC/instances/1.7.10/natives
[04:46:23] [main/DEBUG] [FML/]: Enabling runtime deobfuscation
[04:46:23] [main/DEBUG] [FML/]: Instantiating coremod class FMLCorePlugin
[04:46:23] [main/DEBUG] [FML/]: Added access transformer class cpw.mods.fml.common.asm.transformers.AccessTransformer to enqueued access transformers
[04:46:23] [main/DEBUG] [FML/]: Enqueued coremod FMLCorePlugin
[04:46:23] [main/DEBUG] [FML/]: Instantiating coremod class FMLForgePlugin
[04:46:23] [main/DEBUG] [FML/]: Added access transformer class net.minecraftforge.transformers.ForgeAccessTransformer to enqueued access transformers
[04:46:23] [main/DEBUG] [FML/]: Enqueued coremod FMLForgePlugin
[04:46:23] [main/DEBUG] [FML/]: All fundamental core mods are successfully located
[04:46:23] [main/DEBUG] [FML/]: Attempting to load commandline specified mods, relative to C:\Users\REDACTED\Onedrive - REDACTED - Files\Downloads\MultiMC\instances\1.7.10\.minecraft
[04:46:23] [main/DEBUG] [FML/]: Discovering coremods
[04:46:23] [main/DEBUG] [FML/]: Examining for coremod candidacy AdvancedLightsabers-1.7.10-1.2.2.jar
[04:46:23] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in AdvancedLightsabers-1.7.10-1.2.2.jar, it will be examined later for regular @Mod instances
[04:46:23] [main/DEBUG] [FML/]: Instantiating coremod class ALLoadingPlugin
[04:46:23] [main/DEBUG] [FML/]: The coremod com.fiskmods.lightsabers.asm.ALLoadingPlugin requested minecraft version 1.7.10 and minecraft is 1.7.10. It will be loaded.
[04:46:23] [main/DEBUG] [FML/]: Enqueued coremod ALLoadingPlugin
[04:46:23] [main/DEBUG] [FML/]: Examining for coremod candidacy AdvancedRocketry-1.7.10-1.2.2.jar
[04:46:23] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in AdvancedRocketry-1.7.10-1.2.2.jar, it will be examined later for regular @Mod instances
[04:46:23] [main/DEBUG] [FML/]: Instantiating coremod class AdvancedRocketryPlugin
[04:46:23] [main/DEBUG] [FML/]: The coremod zmaster587.advancedRocketry.asm.AdvancedRocketryPlugin requested minecraft version 1.7.10 and minecraft is 1.7.10. It will be loaded.
[04:46:23] [main/DEBUG] [FML/]: Enqueued coremod AdvancedRocketryPlugin
[04:46:23] [main/DEBUG] [FML/]: Examining for coremod candidacy adventurebackpack-1.7.10-0.8c.jar
[04:46:23] [main/DEBUG] [FML/]: Not found coremod data in adventurebackpack-1.7.10-0.8c.jar
[04:46:23] [main/DEBUG] [FML/]: Examining for coremod candidacy aether-1.7.10-v1.1.2.2.jar
[04:46:23] [main/DEBUG] [FML/]: Not found coremod data in aether-1.7.10-v1.1.2.2.jar
[04:46:23] [main/DEBUG] [FML/]: Examining for coremod candidacy AnimationAPI-1.7.10-1.2.4.jar
[04:46:23] [main/DEBUG] [FML/]: Not found coremod data in AnimationAPI-1.7.10-1.2.4.jar
[04:46:23] [main/DEBUG] [FML/]: Examining for coremod candidacy ArchimedesShips-1.7.1.jar
[04:46:23] [main/DEBUG] [FML/]: Not found coremod data in ArchimedesShips-1.7.1.jar
[04:46:23] [main/DEBUG] [FML/]: Examining for coremod candidacy BiblioCraft[v1.11.7][MC1.7.10].jar
[04:46:23] [main/DEBUG] [FML/]: Not found coremod data in BiblioCraft[v1.11.7][MC1.7.10].jar
[04:46:23] [main/DEBUG] [FML/]: Examining for coremod candidacy BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar
[04:46:23] [main/DEBUG] [FML/]: Not found coremod data in BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar
[04:46:23] [main/DEBUG] [FML/]: Examining for coremod candidacy CodeChickenCore-1.7.10-1.0.7.48-universal.jar
[04:46:23] [main/TRACE] [FML/]: Adding CodeChickenCore-1.7.10-1.0.7.48-universal.jar to the list of known coremods, it will not be examined again
[04:46:23] [main/DEBUG] [FML/]: Instantiating coremod class CodeChickenCorePlugin
[04:46:24] [main/WARN] [FML/]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:46:24] [main/DEBUG] [FML/]: Added access transformer class codechicken.core.asm.CodeChickenAccessTransformer to enqueued access transformers
[04:46:24] [main/DEBUG] [FML/]: Enqueued coremod CodeChickenCorePlugin
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy CodeChickenLib-1.7.10-1.1.3.141-universal.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in CodeChickenLib-1.7.10-1.1.3.141-universal.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy DoggyTalents-1.7.10-1.14.2.317-universal.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in DoggyTalents-1.7.10-1.14.2.317-universal.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy endlessids-mc1.7.10-1.4.0-beta0003.jar
[04:46:24] [main/INFO] [FML/]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from endlessids-mc1.7.10-1.4.0-beta0003.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy GravityGun-1.12.2-7.1.0.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in GravityGun-1.12.2-7.1.0.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy Hats-4.0.1.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in Hats-4.0.1.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy iChunUtil-4.2.3.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in iChunUtil-4.2.3.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy InfernalMobs-1.7.10.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in InfernalMobs-1.7.10.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy inventorypets-1.7.10-1.5.2-universal.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in inventorypets-1.7.10-1.5.2-universal.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy ironchest-1.7.10-6.0.62.742-universal.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in ironchest-1.7.10-6.0.62.742-universal.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy LibVulpes-1.7.10-0.2.8-37-universal.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in LibVulpes-1.7.10-0.2.8-37-universal.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy Mantle-1.7.10-0.3.2b.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in Mantle-1.7.10-0.3.2b.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy MoreCraft-1.7.10-2.7.6.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in MoreCraft-1.7.10-2.7.6.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy Morph-Beta-0.9.3.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in Morph-Beta-0.9.3.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy MutantCreatures-1.7.10-1.4.9.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in MutantCreatures-1.7.10-1.4.9.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy NotEnoughIDs-1.4.3.4.jar
[04:46:24] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in NotEnoughIDs-1.4.3.4.jar, it will be examined later for regular @Mod instances
[04:46:24] [main/DEBUG] [FML/]: Instantiating coremod class IEPlugin
[04:46:24] [main/DEBUG] [FML/]: The coremod ru.fewizz.idextender.IEPlugin requested minecraft version 1.7.10 and minecraft is 1.7.10. It will be loaded.
[04:46:24] [main/DEBUG] [FML/]: Enqueued coremod IEPlugin
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy NotEnoughItems-1.7.10-1.0.5.120-universal.jar
[04:46:24] [main/TRACE] [FML/]: Adding NotEnoughItems-1.7.10-1.0.5.120-universal.jar to the list of known coremods, it will not be examined again
[04:46:24] [main/DEBUG] [FML/]: Instantiating coremod class NEICorePlugin
[04:46:24] [main/WARN] [FML/]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:46:24] [main/DEBUG] [FML/]: Enqueued coremod NEICorePlugin
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy Pam's+HarvestCraft+1.7.10Lb.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in Pam's+HarvestCraft+1.7.10Lb.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy PortalGun-4.0.0-beta-6-fix-1.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in PortalGun-4.0.0-beta-6-fix-1.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy roguelike-1.7.10-1.4.4.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in roguelike-1.7.10-1.4.4.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy SpecialMobs-1.7.10-3.2.2.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in SpecialMobs-1.7.10-3.2.2.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy TConstruct-1.7.10-1.8.8.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in TConstruct-1.7.10-1.8.8.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy TheErebus-0.4.7.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in TheErebus-0.4.7.jar
[04:46:24] [main/DEBUG] [FML/]: Examining for coremod candidacy Zoocraft+Discoveries+1.7.10-1.1.0.jar
[04:46:24] [main/DEBUG] [FML/]: Not found coremod data in Zoocraft+Discoveries+1.7.10-1.1.0.jar
[04:46:24] [main/INFO] [LaunchWrapper/]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[04:46:24] [main/INFO] [LaunchWrapper/]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[04:46:24] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_332]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_332]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_332]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_332]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_332]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_332]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_332]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_332]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[04:46:24] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.reflect.InvocationTargetException
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Runtime.exit(Runtime.java:107)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.System.exit(System.java:973)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 8 more
[04:46:24] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.ArrayIndexOutOfBoundsException: 5
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Runtime.exit(Runtime.java:107)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.System.exit(System.java:973)
[04:46:24] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)

--CONSOLE LOG--

Minecraft process ID: 16776

Using onesix launcher.

[04:46:23] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[04:46:23] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[04:46:23] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[04:46:23] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[04:46:23] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_332, running on Windows 10:amd64:10.0, installed at C:\Users\REDACTED\Onedrive - REDACTED - Files\Downloads\MultiMC\liberica-jdk1.8.0_332-windows-x64\jdk1.8.0_332-windows-x64\java-windows\jre
[04:46:24] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:46:24] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from endlessids-mc1.7.10-1.4.0-beta0003.jar
[04:46:24] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:46:24] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[04:46:24] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[04:46:24] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_332]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_332]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_332]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_332]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_332]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_332]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_332]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_332]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[04:46:24] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.reflect.InvocationTargetException
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Runtime.exit(Runtime.java:107)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.System.exit(System.java:973)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 8 more
[04:46:24] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.ArrayIndexOutOfBoundsException: 5
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Runtime.exit(Runtime.java:107)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.System.exit(System.java:973)
[04:46:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1 (0x1).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Description

Minecraft will not start up when I have EndlessIDs enabled on my instance (I use multiMC but all of my other mods work fine with it, so I don't think the launcher is the problem here), and I have no idea what's causing it, please help thanks.

**Comment by FalsePattern** [comment]
Install GasStation and FalsePatternLib.
