### ISSUE TITLE
[Compatibility Request]: Enderlicious

### ISSUE THREAD

**Issue by zxcvbnma54** [FalsePattern/EndlessIDs#65]
### OS

Windows

### GPU

NVIDIA

### Modpack (Optional)

HardcoreEnderExpansion++MC-1.7.10++v1.8.6.jar，enderlicious-1.1.2.jar

### Game log

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2022/11/1 下午 5:40
Description: Exception generating new chunk

java.lang.UnsupportedOperationException: A mod that is incompatible with EndlessIDs has tried to access the biome array of a chunk like in vanilla! Crashing in fear of potential world corruption!
Please report this issue on https://github.com/FalsePattern/EndlessIDs ASAP!
	at net.minecraft.world.chunk.Chunk.emergencyCrash(Chunk.java:1628)
	at net.minecraft.world.chunk.Chunk.handler$crashGetBiomeArray$zza000(Chunk.java:1642)
	at net.minecraft.world.chunk.Chunk.func_76605_m(Chunk.java)
	at DelirusCrux.Enderlicious.Dimension.EndChunkProvider.func_73154_d(EndChunkProvider.java:365)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at chylex.hee.entity.boss.dragon.managers.DragonChunkManager.onWorldLoad(DragonChunkManager.java:102)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_44_DragonChunkManager_onWorldLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.chunk.Chunk.emergencyCrash(Chunk.java:1628)
	at net.minecraft.world.chunk.Chunk.handler$crashGetBiomeArray$zza000(Chunk.java:1642)
	at net.minecraft.world.chunk.Chunk.func_76605_m(Chunk.java)
	at DelirusCrux.Enderlicious.Dimension.EndChunkProvider.func_73154_d(EndChunkProvider.java:365)

-- Chunk to be generated --
Details:
	Location: 0,0
	Position hash: 0
	Generator: RandomLevelSource
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at chylex.hee.entity.boss.dragon.managers.DragonChunkManager.onWorldLoad(DragonChunkManager.java:102)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_44_DragonChunkManager_onWorldLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1071087472 bytes (1021 MB) / 1744830464 bytes (1664 MB) up to 5335154688 bytes (5088 MB)
	JVM Flags: 7 total; -Xmx5087M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 25, tcache: 68, allocated: 1, tallocated: 21
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAA	xaerominimap_core{1.7.10-1.0} [XaeroMinimapCore] (minecraft.jar) 
	UCHIJAA	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCHIJAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAA	xaeroworldmap_core{1.7.10-1.0} [XaeroWorldMapCore] (minecraft.jar) 
	UCHIJAA	XaeroBetterPvP{21.10.27} [Better PVP Mod] (BetterPvP_21.10.27_Forge_1.7.10-tw.jar) 
	UCHIJAA	HardcoreEnderExpansion{1.8.6} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.6.jar) 
	UCHIJAA	enderlicious{Enderlicious} [§5Enderlicious] (enderlicious-1.1.2.jar) 
	UCHIJAA	falsepatternlib{0.10.11} [FalsePatternLib] (falsepatternlib-mc1.7.10-0.10.11.jar) 
	UCHIJAA	endlessids{1.4.0-beta0003} [EndlessIDs] (endlessids-mc1.7.10-1.4.0-beta0003.jar) 
	UCHIJAA	spongemixins{1.2.0} [SpongeMixins Loader] (SpongeMixins-1.2.0.jar) 
	UCHIJAA	XaeroWorldMap{1.14.1.20} [Xaero's World Map] (XaerosWorldMap_1.14.1.20_Forge_1.7.10-tw.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

### Description

我單獨只安裝這兩個沒問題，可正常進入遊戲，
HardcoreEnderExpansion √ + enderlicious √ = game ok
遊戲就可以正常創建
但是裝了
endlessids √ + HardcoreEnderExpansion √ + enderlicious √ = game no

google translate below：▼

I only install these two separately, no problem, I can enter the game normally,
HardcoreEnderExpansion √ + enderlicious √ = game ok
The game can be created normally
But installed
endlessids √ + HardcoreEnderExpansion √ + enderlicious √ = game no

**Comment by quentin452** [comment]
duplicate #48
