### ISSUE TITLE
[Compatibility Request]: Immersive Engineering

### ISSUE THREAD

**Issue by mcmso** [FalsePattern/EndlessIDs#71]
### Other mod's name

Immersive Engineering

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/immersive-engineering

### Other mod's license

Other open source license (please specify in the description)

### Game log

https://paste.ubuntu.com/p/N8YP4zYzwf/

### Description

I think its license should be Blu's License of Common Sense

[12:54:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: com.falsepattern.endlessids.asm.AsmTransformException: can't find 4095 constant in any method
[12:54:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.falsepattern.endlessids.asm.transformer.FmlRegistry.transform(FmlRegistry.java:36)
[12:54:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.falsepattern.endlessids.asm.IETransformer.transform(IETransformer.java:75)

Hi, I had a crash upon launch, but you don't have to worry, I will provide you with all the information you need
I am sorry that I only have log. If you need other files, please tell me. I will send them to you as soon as possible

**Comment by mcmso** [comment]
I'm sorry that I don't know anything about crash.   I only posted this issue after seeing the word IETransformer.    However, I tried to delete the NotEnoughIDs-1.4.3.4 in modpack later, and his crash became again
crash:https://paste.ubuntu.com/p/nfv6nthTBz/
log:https://bytebin.lucko.me/6V5cXINwyN

**Comment by mcmso** [comment]
> I'm sorry that I don't know anything about crash. I only posted this issue after seeing the word IETransformer. However, I tried to delete the NotEnoughIDs-1.4.3.4 in modpack later, and his crash became again crash:https://paste.ubuntu.com/p/nfv6nthTBz/ log:https://bytebin.lucko.me/6V5cXINwyN

After I tried to delete NotEnoughIDs-1.4.3.4 and 'mod_voxelMap_1.7.0b_for_1.7.10.litemod'
Then it starts up normally
